# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-17 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_photo',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
